"""Recorded provider responses, and the clock that decides when to distrust them.

`core/testes-e-cicd.md` §cassetes: a cassette is generated by a `contract` run,
versioned in the repository, reviewed in a PR like any code, and valid for at
most 30 days. The rule that matters most is the one about what an EXPIRED
cassette does — it makes the nightly run warn and schedule the contract suite;
**it never fails a gate on its own**. So nothing here asserts freshness. There
is a function that answers the question, and it is the nightly's to call: a
blocking suite that failed on the calendar would fail on a Monday nobody
touched the code, which is how a policy becomes something people disable.

`recorded_at` is nullable and null means "never recorded". A hand-written
stand-in is a legitimate thing to have — it pins our translation against a
shape we believe — but it must not be able to pass for a recording, so the
loader carries the distinction rather than flattening it.
"""

import json
from datetime import UTC, datetime, timedelta
from pathlib import Path
from typing import Any

CASSETTES = Path(__file__).parents[1] / "cassettes"

#: `core/testes-e-cicd.md` §política de cassetes.
MAX_AGE = timedelta(days=30)


def load(name: str) -> dict[str, Any]:
    return json.loads((CASSETTES / f"{name}.json").read_text(encoding="utf-8"))


def recorded_at(cassette: dict[str, Any]) -> datetime | None:
    """When the provider actually answered — `None` when it never has."""
    raw = cassette.get("recorded_at")
    return datetime.fromisoformat(raw) if raw else None


def is_stale(cassette: dict[str, Any], *, now: datetime, max_age: timedelta = MAX_AGE) -> bool:
    """Whether the nightly should schedule a contract run for this provider.

    A cassette that was never recorded is stale by definition: it is a belief
    about a provider, and a belief is exactly what the contract suite exists to
    convert into evidence. `now` is a parameter because a helper that read the
    clock could not be tested without waiting a month.
    """
    at = recorded_at(cassette)
    return at is None or (now - at) > max_age


def rerecord(name: str, responses: dict[str, Any], *, at: datetime) -> None:
    """Write what the provider just said. Called only from `tests/contract/`.

    The write happens in a developer's working tree and reaches main as an
    ordinary PR — which is the point of the policy: if the provider's new shape
    breaks a blocking test, the break shows up in the cassette's own PR, with a
    human as the approver, instead of arriving inside somebody else's change.
    """
    path = CASSETTES / f"{name}.json"
    cassette = json.loads(path.read_text(encoding="utf-8"))
    cassette["responses"] = responses
    cassette["recorded_at"] = at.astimezone(UTC).isoformat()
    cassette["source"] = "recorded by tests/contract/ against a real store"
    cassette.pop("why_null", None)
    path.write_text(json.dumps(cassette, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
