"""O fio ponta a ponta volta — evento → cadência → escada → outbox → canal.

The E1 proof (`test_scenario_abandonment`) died with the fixed-text touch (D6),
and since S3 nothing has reached a channel at all: the cadence was scheduled and
the milestone deliberately stopped there, because the ladder did not exist yet.
This is the same thread, whole, with every gate of the milestone in it:

    webhook → ingest_webhook → q_domain_events → apply_domain_event →
    start_funnel_run → scheduled_touches → claim_due_touches → q_scheduled →
    the ladder → dispatch_touch's CAS → message_outbox → sender → the channel

Nothing is patched. The composition is the real one (`app.run`), the roles are
the production roles (`worker_role`, `sender_role`), and the only doubles are
the ones that would otherwise cost money or a phone number.

The stopping condition follows decisão 61: the LAST observable of the flow — the
channel holding the message — never an intermediate state.
"""

import asyncio
from dataclasses import replace
from datetime import timedelta

import psycopg
import pytest
from psycopg.types.json import Jsonb

from agents_runtime.app import run
from agents_runtime.config import QueueingConfig
from tests.db.factories import (
    create_channel_account,
    create_connector_account,
    create_tenant,
    create_thread,
    unique_id,
    unique_phone,
)
from tests.db.factories_e3 import create_funnel, create_scheduled_touch
from tests.pipeline.test_scenarios_a import DEADLINE, eventually
from tests.support.database import as_runtime_worker
from tests.support.fake_channel import FakeChannel

CADENCE = [
    {"n": 1, "delay": "PT0S", "copy_base": "Vi que ficou algo no carrinho."},
    {"n": 2, "delay": "PT6H", "copy_base": "Ainda dá tempo."},
]


async def test_an_abandonment_becomes_a_touch_the_contact_receives(
    dsn: str,
    admin: psycopg.AsyncConnection,
    sync_admin: psycopg.Connection,
    tiny_config: QueueingConfig,
) -> None:
    tenant_id = create_tenant(sync_admin)
    store = create_connector_account(sync_admin, tenant_id)
    create_channel_account(sync_admin, tenant_id)
    funnel = create_funnel(sync_admin, tenant_id, touches=CADENCE)
    phone = unique_phone()

    outcome = sync_admin.execute(
        "select * from internal.ingest_webhook('shopify', %s, %s, 'checkout_abandoned', %s)",
        (store.source_account_id, unique_id("evt"), Jsonb({"phone": phone})),
    ).fetchone()
    assert outcome[0] == "ingested"

    # The sweep runs on the canonical minute in production; the milestone's
    # rhythms are config, and this is the one the pipeline shortens.
    config = replace(tiny_config, dispatcher_tick=timedelta(milliseconds=50))

    stop = asyncio.Event()
    running = asyncio.create_task(
        run(
            dsn,
            stop=stop,
            config=config,
            channel=FakeChannel(dsn),
            worker_set_role="worker_role",
            sender_set_role="sender_role",
        )
    )
    try:

        async def delivered():
            cursor = await admin.execute(
                "select payload, to_phone_e164 from testing.fake_channel_sends"
            )
            return await cursor.fetchone()

        send = await eventually(delivered, note="the first touch reaching the channel")
    finally:
        stop.set()
        await asyncio.wait_for(running, DEADLINE)

    # The copy is the cadence's, deterministically, and it is marked as not
    # generated by a model (D3c) — variação anti-ban é do S7.
    assert send == ({"text": "Vi que ficou algo no carrinho.", "generated": False}, phone)

    # Touch nº 1 went out and says so; touch nº 2 is six hours away and was not
    # touched by the sweep. `max_touches` is the funnel's ceiling, and the
    # per-contact protections are the ladder's.
    touches = await (
        await admin.execute(
            """
            select t.touch_number, t.status, t.sent_at is not null, t.outbox_id is not null
              from public.scheduled_touches t
             where t.funnel_id = %s
             order by t.touch_number
            """,
            (funnel.id,),
        )
    ).fetchall()
    assert touches == [(1, "sent", True, True), (2, "pending", False, False)]

    # And the whole spine agrees: one outbox row, delivered, and the
    # conversation contains what the store said.
    spine = await (
        await admin.execute(
            """
            select (select count(*) from internal.message_outbox where status = 'sent'),
                   (select count(*) from internal.message_outbox),
                   (select count(*) from public.messages where direction = 'outbound'),
                   (select count(*) from public.messages where direction = 'inbound')
            """
        )
    ).fetchone()
    assert spine == (1, 1, 1, 0)


async def test_the_sweep_never_marks_a_touch_it_could_not_enqueue(
    dsn: str, admin: psycopg.AsyncConnection, sync_admin: psycopg.Connection
) -> None:
    """Claim and enqueue commit together, or neither does.

    The failure this forbids is silent and permanent: a touch marked `enqueued`
    with no job to fire it is a touch nobody will ever look at again, and the
    only symptom is a merchant wondering why a funnel stopped. It is the same
    reason the coalescer sends inside its own transaction.
    """
    from agents_runtime.queueing.dispatcher import dispatch_pass

    tenant_id = create_tenant(sync_admin)
    thread = create_thread(sync_admin, tenant_id)
    funnel = create_funnel(sync_admin, tenant_id, touches=CADENCE)
    touch_id = create_scheduled_touch(
        sync_admin,
        tenant_id,
        funnel.id,
        thread.contact_id,
        conversation_id=thread.conversation_id,
        due_in_seconds=-60,
    )

    async with as_runtime_worker(dsn) as conn:
        with pytest.raises(psycopg.Error):
            await dispatch_pass(conn, queue="q_that_does_not_exist")

    status = sync_admin.execute(
        "select status from public.scheduled_touches where id = %s", (touch_id,)
    ).fetchone()[0]

    assert status == "pending"


async def test_a_suppressed_contact_is_never_touched_by_the_running_engine(
    dsn: str,
    admin: psycopg.AsyncConnection,
    sync_admin: psycopg.Connection,
    tiny_config: QueueingConfig,
) -> None:
    """RF-033 with the engine running: the list is checked before EVERY
    proactive send, and the touch dies with the ladder's own word for it."""
    tenant_id = create_tenant(sync_admin)
    store = create_connector_account(sync_admin, tenant_id)
    create_channel_account(sync_admin, tenant_id)
    create_funnel(sync_admin, tenant_id, touches=CADENCE)
    phone = unique_phone()

    # The block exists BEFORE the abandonment, so nothing here depends on
    # winning a race against the sweep. `start_funnel_run` upserts the contact
    # by phone and finds this one.
    contact_id = sync_admin.execute(
        "insert into public.contacts (tenant_id, phone_e164) values (%s, %s) returning id",
        (tenant_id, phone),
    ).fetchone()[0]
    sync_admin.execute(
        """
        insert into public.suppression_list (tenant_id, contact_id, reason, created_by)
        values (%s, %s, 'explicit_block', 'agent')
        """,
        (tenant_id, contact_id),
    )

    sync_admin.execute(
        "select * from internal.ingest_webhook('shopify', %s, %s, 'checkout_abandoned', %s)",
        (store.source_account_id, unique_id("evt"), Jsonb({"phone": phone})),
    )
    config = replace(tiny_config, dispatcher_tick=timedelta(milliseconds=50))

    stop = asyncio.Event()
    running = asyncio.create_task(
        run(
            dsn,
            stop=stop,
            config=config,
            channel=FakeChannel(dsn),
            worker_set_role="worker_role",
            sender_set_role="sender_role",
        )
    )
    try:

        async def cancelled():
            cursor = await admin.execute(
                "select cancel_reason from public.scheduled_touches"
                " where status = 'cancelled' and touch_number = 1"
            )
            return await cursor.fetchone()

        reason = await eventually(cancelled, note="the touch cancelled by the ladder")
    finally:
        stop.set()
        await asyncio.wait_for(running, DEADLINE)

    assert reason == ("suppressed_block",)

    silence = await (
        await admin.execute(
            "select (select count(*) from testing.fake_channel_sends)"
            " + (select count(*) from internal.message_outbox)"
        )
    ).fetchone()
    assert silence == (0,)
